Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -20,9 +20,10 @@ pool:
   name: "default"
 
 steps:
-- bash:
+- bash: |
     if [ -e $CATALOG_DESCRIPTOR ]
     then
+      # Update catalog meta-data 
       mkdir -p $TMP_DIR
       
       if [ -d $TMP_DIR ]
@@ -34,7 +35,8 @@ steps:
       cat $API_FILE
       
       api-catalog update-descriptor 
-      
+
+      # Publish API      
       api-catalog publish-asset \
       --organization $ANYPOINT_ORG \
       --host=$ANYPOINT_HOST \
@@ -44,6 +46,7 @@ steps:
       
       cat catalog-result.txt
       
+      # Capture latest version
       while IFS= read -r line
       do
         echo $line
@@ -59,11 +62,53 @@ steps:
     else
       exit 1
     fi
+  displayName: 'Catalog and validate'
 
-- script: echo Hello, world!
-  displayName: 'Run a one-line script'
+- bash: |
+    # Save ruleset for later
+    cp openapi-best-practices-ruleset.yaml $TMP_DIR
+    
+    VERSION=$(<version.txt)
+    
+    # Download new asset
+    anypoint-cli exchange asset download package-tracker-api/$VERSION $TMP_DIR \
+        --organization $ANYPOINT_ORG \
+        --host=$ANYPOINT_HOST \
+        --environment=$ANYPOINT_ENV
+  displayName: 'Download asset from Exchange'
 
-- script: |
-    echo Add other tasks to build, test, and deploy your project.
-    echo See https://aka.ms/yaml
-  displayName: 'Run a multi-line script'
+- bash: |
+    # Validate API
+    
+    # Move and unzip file
+    unzip -o $TMP_DIR/*.zip -d $TMP_DIR
+    ls $TMP_DIR
+    anypoint-cli governance api validate --rulesets  $TMP_DIR/openapi-best-practices-ruleset.yaml $TMP_DIR/*.zip \
+    --organization $ANYPOINT_ORG \
+    --host=$ANYPOINT_HOST \
+    --environment=$ANYPOINT_ENV > output.txt
+    
+    cat output.txt
+    
+    # If output indicates error then stop
+    if [[ ! $(grep "Spec conforms with Ruleset" output.txt) ]] ; then
+        echo "Failed validation"
+        exit 1
+    else
+        echo "Failed paswed"
+    fi
+  displayName: 'Validate against ruleset'
+
+- bash: |
+    docker run --rm -v "$(pwd):/data" \
+        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
+        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
+        -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
+        amazon/aws-cli \
+        apigateway put-rest-api \
+        --cli-binary-format raw-in-base64-out \
+        --rest-api-id $AWS_API_ID \
+        --mode overwrite \
+        --body "file:///data/$API_FILE"
+
+  displayName: 'Update AWS API Gateway'
